### PR TITLE
Add package for react web apps

### PR DESCRIPTION
**Pull request by davidharting**
Implements an eslint config package for React-based web apps.

### CODE REVIEW

**Comment by emmoistner** [comment]
Probably docs to base repo readme as well

**Comment by davidharting** [comment]
@emmoistner What if I moved the documentation for `backend` into the backend package, and then created a new general README at the base repo level as well? 

That  way we don't have to duplicate information in every package.

**Comment by davidharting** [comment]
e.g., checkout recent commit @emmoistner. Not married to it, but I think it makes sense to avoid duplication.

**Comment by emmoistner** [comment]
Cool, just link out to each package maybe? easy to follow?

**Comment by davidharting** [comment]
@emmoistner How's ^this look to ya?

**Comment by emmoistner** [comment]
Yup, there is also bug currently with how dependencies are resolved. 

**Issue**
I think we have to have eslint-airbnb-airbnb as a devDependency for the project.
Setup would be 
```bash
// Web
npm install eslint-config-airbnb --save-dev && npm install eslint-config-emplify-react-web
// Backend
npm install eslint-config-airbnb-base --save-dev && npm install eslint-config-emplify-backend
```

**Comment by davidharting** [comment]
Okay I will add the dev dependency and adjust the docs for web and backend.

**Comment by davidharting** [comment]
I was able to test this locally (you can NPM install files) and everything seems to work.

I enhanced the README to specify in more detail how you get completely set up for linting.

Once I get approval, I will merge and then create a release so that this can get published to npm.

**Pull request merged**
